# Generated by Django 4.2.1 on 2023-05-29 09:46

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contect1', ckeditor.fields.RichTextField()),
                ('contect2', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
