# Generated by Django 4.2.1 on 2023-05-29 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='contect1',
            new_name='contect',
        ),
        migrations.RemoveField(
            model_name='about',
            name='contect2',
        ),
    ]
