# Generated by Django 4.2.1 on 2023-05-29 10:42

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_contect_about_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_text', ckeditor.fields.RichTextField()),
                ('development_text', ckeditor.fields.RichTextField()),
                ('database_text', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
